### ISSUE TITLE
Add project build tool

### ISSUE THREAD

**Issue by derrykid** [Alencaminha/Java-Swing-Store-Management-App#1]
Do you consider add a build tool? e.g. maven, or gradle.

**Comment by Alencaminha** [comment]
Hi, thanks for asking. I wasn't going to, but since you asked, I've just added Maven to the project. Since this was just a simple project for me to practice Java, Swing and MySQL I have no current plans to add unit tests. Anyways, if you find any problems with the current build feel free to open another issue.
